version: '3.4'
services:

  indypool:
    network_mode: host
    image: "teamblockchain/indy-pool:1.7.0"
    ports:
      - "9701-9708:9701-9708"
    container_name: indypool

  webbaseimage:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile-web
      target: libindyjava
    image: libindyjava

  # -------------------- Spring nodes -----------------------

  webapp:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:8080"
    environment:
      - "INDY_AGENT_ENDPOINT=ws://localhost:8095/ws"
      - "INDY_AGENT_USER=credential-issuer"
      - "INDY_AGENT_PASSWORD=password"
      - "INDY_GENESIS_PATH=genesis/docker_localhost.txn"
    container_name: webapp

  # -------------------- Indy agents -----------------------
  agent94:
    image: teamblockchain/indy-agent-python:eee0475e1ac3417990a4ec55164b1a32eb3bd6d5
    ports:
      - "8094:8094"
    environment:
      - "PORT=8094"
    hostname: agent
    #    volumes:
    #     - ./hosts:/etc/hosts:ro
    container_name: agent94

  agent95:
    image: teamblockchain/indy-agent-python:eee0475e1ac3417990a4ec55164b1a32eb3bd6d5
    ports:
      - "8095:8095"
    environment:
      - "PORT=8095"
    hostname: agent
    #    volumes:
    #      - ./hosts:/etc/hosts:ro
    container_name: agent95

  agentInitiator:
    network_mode: host
    image: alpine:3.6
    container_name: agentInitiator
    depends_on:
      - agent94
      - agent95
    command: sh -c 'sleep 10; /usr/bin/wget --spider http://localhost:8094/; /usr/bin/wget --spider http://localhost:8095/'
